name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2.2.0
        with:
          go-version: ^1.17

      - name: Make
        run: make
