name: Release

on:
  push:
    branches: [master]

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Setup Sage
        uses: einride/sage/actions/setup@master
        with:
          go-version-file: .sage/go.mod

      - name: Make
        run: make

      - name: Release
        uses: go-semantic-release/action@v1.24
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true
